freifunk-berlin/falter-packages

- packages/falter-berlin-network-defaults/uci-defaults/freifunk-berlin-correct-nsm2-txpower
As of upstream commit 1fdf6b745cc3d85be3743837817a360121554134 the
"which" command is not longer being used and instead "command -v",
which itself is POSIX compliant, is being used treewide.  In addition
there are plans to remove the "which" command to save a bit of space.
> falter-berlin-network-defaults: use "command -v" instead of "which"

- packages/falter-berlin-tunneldigger/Makefile
Switch to https instead of ssh. Could solve problems if ssh is blocked.
Bump to latest version.
> falter-berlin-tunneldigger: bump version and switch to https

- packages/falter-common/files-common/etc/config/freifunk
The wizard crashed if you tried to configure a 5GHz adhoc mesh.
Fixes #9.
> luci-app-ffwizard-falter: fix 5 GHz adhoc mesh configuration

- packages/falter-common/Makefile
- packages/falter-common/files-olsrv1/usr/bin/hna.lua
This commit adds a new package falter-berlin-network-tools.
Currently it only contains the hna.lua-script for showing HNAs known to the router. In the future, `neigh.sh` and more tools to be written might move into this package.
> add package falter-berlin-network-tools.

- luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua
Add OLSRv2 to front page if it is installed.
> luci-mod-falter: add olsrv2 to front page

- luci/luci-app-ffwizard-falter/Makefile
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/changePassword.lua
Up until now, after having run the wizard, once logging in the user
would be prompted to enter a new password again.  This is now changed
via a redirect which checks to see if the password has already been set
and that the wizard has already ran.
cherry-picked from 06aa021d6534fbd96f8b77fd0385a2adae95c000 on the openwrt-19.07 branch.
Fixes: #11
> luci-app-ffwizard-falter: No longer ask for passwords unnecessarilly

- packages/falter-berlin-bbbdigger/Makefile
- packages/falter-berlin-bbbdigger/files/postinst.sh
bbbdigger was widely requested by several people, but missing
in falter package feed. This commit adds it.
> openwrt-19.07:falter-berlin-bbbdigger: Add bbbdigger to falter package feed.

- packages/falter-berlin-bbbdigger/Makefile
- packages/falter-berlin-bbbdigger/files/postinst.sh
bbbdigger was widely requested by several people, but missing
in falter package feed. This commit adds it.
> falter-berlin-bbbdigger: Add bbbdigger to falter package feed.

- luci/luci-app-ffwizard-falter/Makefile
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/changePassword.lua
Up until now, after having run the wizard, once logging in the user
would be prompted to enter a new password again.  This is now changed
via a redirect which checks to see if the password has already been set
and that the wizard has already ran.
Fixes: #11
> opernwrt-19.07: luci-app-ffwizard-falter: No longer ask for passwords unnecessarilly

- packages/falter-common/Makefile
- packages/falter-common/files-common/etc/profile.d/dynbanner.sh
This package embeds regularily dynamic system information (i.e. system load,
uptime, amount of clients) into the banner. To protect the flash (limited amounts of writing cycles),
it uses tmpfs to store the new banner.
> falter-common: add /etc/profile.d/dynbanner.sh

- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
With the creation of the file /etc/freifunk_release we
now have a method of versioning independant from openWrt.
In order for the migration script to work, the file 
/etc/freifunk_release will need to be isntalled, otherwise the
migration script will just exit.  This is for images build with
the new builter tool.
The current migration script is not yet up to date with the
current state of falter.  That shall be done later.
> falter-berlin-migration: integrate new versioning

- packages/falter-common/files-common/etc/config/freifunk
Set the default mcast_rate for 802.11s to 12000.  This
value is derived from the experiences made at Freifunk Berlin
and the best working value for both 2.4 and 5Ghz for the
largest running 802.11s mesh-island in the network.
> falter-common: set default mcast_rate for 802.11s

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
- packages/falter-berlin-migration/uci-defaults/zz_freifunk-berlin-migration-clean_jffs.sh
Here is the first wave of migration scripts.  Covered are
* handle profiles
Upon upgrade, the files /etc/config/profile_* and /etc/config/freifunk are not automatically upgraded to the newest version.  This commit pulls the profile_* out of the rom partition and overwrites the profiles in /etc/config.
Additionally the freifunk config is handeled seperately.  This config file is a mixure of defaults with the addition of the 'contact' and 'community' sections which are configured for the running system. In this case, the version from rom is copied into /etc/config and the 'contact' and 'community' sections from the old setup are imported.
* update statistics server
* convert wireless to 802.11s
Sets all the adhoc devices to 802.11s, including changing the settings in statistics and …
> falter-berlin-migration: Hedy to falter migration, wave 1

- luci/luci-app-ffwizard-falter/luasrc/controller/assistent/assistent.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/changePassword.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/startWizard.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
Add the ability to have an after-upgrade wizard, or simply called upgrades.  In the upgrade folder lua pages can be add in further releases which will prompt the user to make a decision.  The lua pages are named NNN_task.lau.  The pages are executed in alphabetical order.
ffwizard.upgrade.lastUpgrade
An new section in the ffwizard config has been created to remember which upgrade was ran last.  This value is also set automatically upon finishing the wizard.
The migration from adhoc to 802.11s is added as a sample page.  The affected config files are ffwizard, wireless, and luci_statistics.  
As a bonus, the Freifunkassistent is removed from the menu.
This PR is dependent on PR #72. 
fixes: #66
> ffwizard: add manual migration steps to luci

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
Set the names of the wifi-iface sections to, for exampe,
wlan0_dhcp_5.
> luci-app-ffwizard-falter: set wifi-iface section names

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
In this batch of updates, the changes to defaults, the ntp section in system, uhttpd, and ucitrack are updated.
> falter-berlin-migration: add more updates to OpenWrt 19.04 (wave 2)

- packages/falter-common/files-common/etc/freifunk_release
Set the FREIFUNK_RELEASE and FREIFUNK_OPENWRT_BASE variables
in /etc/freifunk_release.
The FREIFUNK_RELEASE variable should be in the form X.Y.Z for
a release, X.Y.Z-rcR for a release candidate, X.Y.Z-betaB for
a beta test, or X.Y.Z-snapshot for the OpenWrt snapshot releases.
The FREIFUNK_OPENWRT_BASE variable should be the name of the OpenWrt
branch that the firmware is based off of.  For example, "openwrt-19.07"
or "master"
Currently the builter repo sets this file in embedded_files.  Removing
this from builter is a requirement for merging.
> falter-packages: add /etc/freifunk_release to falter-common

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
- luci/luci-app-ffwizard-falter/luasrc/tools/freifunk/assistent/tools.lua
Add the ability to check the current driver to see which modes
"802.11s" or "Ad-hoc" are supported.  Only give the user the option
to select a mode if it is a valid mode.  This can be seen on
both the wireless wizard page and on the wireless mesh upgrade
page.
> luci-app-ffwizard-falter: check mesh modes in wizard

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
Changing from 802.11s to adhoc fails because of an undeclared
variable. This is a copy-paste error from the code used in the
wizard.
Error introduced in 5e8b69c
> luci-app-ffwizard-falter: fix upgrade wireless-mesh

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua
- luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua
In luci-mod-falter, add reference to load the Wireless Mesh settings page
In luci-app-ffwizard-falter: add the Wireless Mesh setting page.  This provides the admin the ability to switch a radio between 802.11s and adhoc.  The page is very similar to the upgrade page for 802.11s but has a few very destinct differences.
Fixes: #83
> Add wireless mesh setting page

- packages/falter-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults
I wrote a collectd plguin for replacing the exec script. It is merged
in the master:
- https://github.com/openwrt/packages/pull/14204
The collectd upstream PR:
- https://github.com/collectd/collectd/pull/3790
We need to add "collectd-mod-dhcpleases" to packagelist.
> falter-berlin-statistics-defaults: add dhcpleases

- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/map.htm
Fixes #34.
When you click on the map the coordinates should be entered into the
fields above the map.
The ID was wrong. Changed to
- widget.cbid.ffwizward.1.lat
- widget.cbid.ffwizward.1.lon
> luci-app-ffwizard-falter: fix map

- luci/luci-app-falter-owm/Makefile
- luci/luci-app-falter-owm/luasrc/Makefile
- luci/luci-app-falter-owm/luasrc/owm.lua
Use the values in /etc/freifunk_release in the data sent by /usr/sbin/owm.lua.  If the file does not exist, the program runs like always.
Additionally, stop compiling the lua source.
fixes #96
> Add freifunk release support to owm

- packages/falter-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
What is the problem?
syslog is spammed by: daemon.warn dnsmasq-dhcp: DHCP packet received on xxx-wan which has no address
What is the expected behaviour?
dnsmasq should not care / be silent for 'wan'
Signed-off-by: everloop2 <25203855+everloop2@users.noreply.github.com>
> freifunk-berlin-dhcp-defaults: dnsmasq: ignore wan

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
- packages/falter-berlin-statistics-defaults/uci-defaults/freifunk-berlin-statistics-defaults
falter-berlin-statistics-defaults: Update default for memory plugin
Add the option ValuesAbsolute=1 to the memory plugin
falter-berlin-migration: add statistics migration
Fixes: #112
> fater-berlin.statistics-defaults: set option ValuesAbsolute=1 in luci_statistics

- packages/falter-berlin-uplink-notunnel/uci-defaults/freifunk-berlin-z95_notunnel
When switching from tunneldigger to notunnel, the setting in tunneldigger
for the ffuplink should be disabled.  Without disabling this, the
notunnel setting for ffuplink will not work properly.
Fixes: #119
> falter-berlin-uplink-notunnel: disable tunneldigger setting for ffuplink

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua
the variable devconfig.channel was referenced, but is undefined.  Use
devChannel instead
Fixes: #121
> luci-app-ffwizard-falter: fix wireless-mesh settings page

- luci/luci-app-ffwizard-falter/Makefile
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
- packages/falter-berlin-network-defaults/Makefile
- packages/falter-berlin-network-defaults/uci-defaults/freifunk-berlin-ffuplink-defaults
falter-berlin-network-defaults: disable ffuplink per default
disable the ffuplink per default and only activate it if the user decides to activate the ffuplink interface in the wizard by choosing to share the internet connection
luci-app-ffwizard-falter: only enable ffuplink when chosen
only enable the ffuplink interface if the user decides to share their internet connection.
Fixes #123
> Disable ffuplink interface durring initial setup

- luci/luci-app-olsr2/Makefile
Move the dependencies from LUCI_DEPENDS to LUCI_EXTRA_DEPENDS to reduce
the amount of compile-time dependencies
Fixes: #105
> luci-app-olsr2: move LUCI_DEPENDS to LUCI_EXTRA_DEPENDS

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
when ffwizard.settings.sharenet is not set to 1 (don't share),
then set the ffuplink interface to disabled=1.  Otherwise the
policy routing will not provide internet (desired) but still
olsrd will advertise and up (black hole/not desired).
if sharing is desired (set to 1), then explicitly set the ffupink
to disabled=0
Fixes: #126
> falter-berlin-migration: handle sharenet

- packages/falter-berlin-network-defaults/lib/functions/freifunk-berlin-network.sh
set the option peerdns to 0 for ffuplink.  This prevents the interface
from adding the local router's advertised DNS servers to dnsmasq running
on the router.  This only has a real impact on the notunnel version as
none of the tunneldigger servers advertise DNS.
Fixes: #130
> falter-berlin-network-defaults: no peerdns for ffuplink

- luci/luci-app-falter-owm/luasrc/owm.lua
$(check for nil position and do not set position then)
Fixes #136
> luci-app-falter-owm: fix crash on empty lat/lon

- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/bbbdigger.lua
- luci/luci-mod-falter/root/usr/share/rpcd/acl.d/luci-mod-falter.json
Add the ability to enable (create if not already created) or
disable the bbbdigger interface.  If the interface and related
settings have not been created before, use the default values
hard coded into the page.  If the interface and related settings
have been created before, simple toggle between disabled=1 and
disabled=0 as necessary.
This is a very Berlin centric page and is not easily portable
to other communities.  If portablility to other communitites is
required, then a rework of the settings should be considered.
Fixes: #54
> luci-mod-falter: add BBB-VPN (bbbdigger) config page

- luci/luci-mod-falter/root/lib/upgrade/keep.d/freifunk
add the file /www/luci-static/index_user.html to /lib/upgrade/keep.d
to ensure that after an upgrade "user defined inex pages" are kept.
Fixes: #147
> luci-mod-falter: add index_user.html to sysupgrade keep list

- packages/falter-common/files-common/etc/profile.d/dynbanner.sh
For nodes that do not host a DHCP-Server count the clients will produce
an error message, as the file /tmp/dhcp.leases doesn't exist. The error
shouldn't appear in the dynbanner. Thus we suppress it by piping the error
output to /dev/null.
Fixes #157.
> falter-common: suppress error on missing file

- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/bandwidth.lua
Maintainer: me
Compile tested: none
Run tested: TP-Link WDR4900 V1
Description: allow the user to modify the bandwidth settings.
Fixes: #170
> luci-mod-falter: add bandwidth settings page

- luci/luci-app-ffwizard-falter/Makefile
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua
- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Maintainer: me
Compile tested: None, only run tested
Run tested: TP-Link CPE210 V1, Falter Firmware 1.1.0
Description:
The RSSI Leds will cause a high load when the referenced device (system.rssi_$WLAN.dev) is not set to a proper wlan interface.  These commits will set the RSSI Leds device to the wireless mesh interface (either adhoc or 802.11s).
Fixes: #142
> RSSI Led device setting

- TRANSLATION.md
- fetch_translation_tools.sh
This adds a short tutorial on how to translate a luci app.
Description:
> TRANSLATION.md: add tutorial on luci app translation

- README.md
This commit adds some further information on the general falter
repo structure. Hopefully this will lower the bar to get involved
into firmware development.
Description:
> README.md: add section on general repo structure

- packages/falter-berlin-ssid-changer/Makefile
- packages/falter-berlin-ssid-changer/files/lib/lib_ssid-changer.sh
- packages/falter-berlin-ssid-changer/files/offline.d/ssid-changer_isOffline.sh
- packages/falter-berlin-ssid-changer/files/online.d/ssid-changer_isOnline.sh
If one node hasn't got any connection to the internet it's
ssid gets changed to some string that says its offline.
It uses the pingcheck package for determining that.
This is intended for raising the user experience by avoiding
the broadcast of conectionless WiFis.
Description:
This would fix #4
> ssid-changer: Add package ssid-changer

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua
Maintainer: me
Run tested: (mpc85xx, wdr4900, falter 1.1.1, runtest)
Description: check for null on each wireless device, sanity check
If the user were to delete a wireless mesh interface or has a wireless
device which does not support either adhoc or 802.11s, then it can lead
to a situation where a null pointer is referenced.
Fixes: #177
> Mesh settings check for null

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
The file /etc/opkg/customfeed.conf gets preserved at sysupgrades.
Thus we need to migrate the feed url to point to the new falter
release.
Description:
This should be cherry-picked into 21.02 and 19.07 too. (please use -x option)
> falter-berlin-migration: add migrations for 1.1.2

- luci/luci-app-falter-owm/Makefile
- luci/luci-app-falter-owm/files/owm.sh
IPv6 becomes now first lookup. So localhost resolves to ::1. oslr is not listening on ::1 if you have not enabled olsrd6 which we don't use.
> luci-app-falter-owm: use 127.0.0.1 instead of localhost

- RELEASE.md
At the last release we had an issue with the buildbot, as the
timeout for builds was not emphasised enough.
Description:
> RELEASE.md: Underline buildbot timeout

- packages/falter-berlin-firewall-defaults/Makefile
- packages/falter-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults
According to the OpenWRT documentation
(https://openwrt.org/docs/guide-user/firewall/firewall_configuration)
syn_flood is depricated and should be replaced using synflood_protect.
Fixes: #178
> falter-berlin-firewall-defaults: synflood_protect update

- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Newly added migration functions include:
ensure_profiled
r1_2_0_dhcp
r1_2_0_fw_zone_freifunk
r1_2_0_fw_synflood
r1_2_0_statistics
r1_2_0_network
r1_2_0_olsrd
r1_2_0_owm
r1_2_0_dynbanner
Fixes: #215
Fixes: #214
Fixes: #211
Fixes: #178
> falter-berlin-migration: updates for openwrt 21.02.0

- packages/falter-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
using the device option in a firewall zone is deprecated, and instead is made as a list.
There is no need to bump the pkgver since this commit is basically back-to-back with d0e572d
Fixes: #223
> change firewall zone device from option to list

- packages/falter-berlin-tunneldigger/Makefile
The kernel module l2tp-ip is not needed, removed from the dependency
list.
Fixes: #222
> falter-berlin-tunneldigger: remove dependency on kmod-l2tp-ip

- luci/luci-mod-falter/po/de/falter.po
- luci/luci-mod-falter/po/en/falter.po
- luci/luci-mod-falter/po/templates/falter.pot
PR #235 added the swap-page, which swaps the roles of the
ethernet ports on the router. This commit adds the German translation
for that page.
Description:
> luci-mod-falter: add translation for swap-page

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Add migration for bbbdigger typo
Fix the typo from previous versions
Bug introduced in 9ab7a8595ec24315de2112ffed439797a16d934b
and fixed in f38bc2b6e0a7691a84be9115603cb2a7e5b1be0e
Fixes: #232
> 1.1.3 migration bbbdigger typo

- luci/luci-mod-falter/luasrc/model/cbi/freifunk/basics.lua
- luci/luci-mod-falter/po/de/falter.po
- luci/luci-mod-falter/po/en/falter.po
- luci/luci-mod-falter/po/templates/falter.pot
The text on changing community-profiles was misunderstood
by some users. This introduces a better wording.
Fixes: #199
please cherry-pick to 21.02 and 19.07
> luci-mod-falter: fix confusing wording

- packages/falter-berlin-tunneldigger/Makefile
- packages/falter-berlin-tunneldigger/files/tunneldigger.hotplug
- packages/falter-berlin-tunneldigger/files/tunneldigger.init
Add support for option srv to /etc/config/tunneldigger, which denotes an SRV DNS entry.  This can be used instead or with the address list.  The advantage of using an srv, is that only on the dns server side do we need to modify the list as servers are added/removed.
Add optional to the init script.  The start, stop and restart function can take arguements.  Without any arguements, the default behavior is to start/stop/restart all tunneldigger sections.  With arguements, only the listed tunneldigger sections are started/stopped/restarted
Fixes #220
> Add DNS SRV support to tunneldigger, improve init script

- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/bbbdigger.lua
- packages/falter-berlin-bbbdigger/Makefile
- packages/falter-berlin-bbbdigger/files/postinst.sh
- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
- packages/falter-berlin-uplink-tunnelberlin/Makefile
- packages/falter-berlin-uplink-tunnelberlin/uci-defaults/freifunk-berlin-z95_tunnelberlin-tunneldigger
Migrate all tunneldigger sections from address list to srv option.
This has been possible since commit 29943b0
> Move tunneldigger configs to srv

- CONTRIBUTING.md
This commit adds a contribution guideline. This is a preparation
for hacktoberfest.
Description:
> CONTRIBUTING.md: add contribution guideline

- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/po/de/falter.po
Fix a type in the translation for luci-mod-falter:
"Sptzname" -> "Spitzname"
Fixes: #252
> luci-mod-falter: fix translation string "Sptzname"

- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/po/de/falter.po
Fix a typo in the translation for luci-mod-falter:
"Sptzname" -> "Spitzname"
Fixes: #252
> luci-mod-falter: 1907 fix translation string "Sptzname"

- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Modified the firewall zone routine to migrate all zone
Updated the statistics routine to set enable to the same
value as luci_statistics.collectd_interface.enable so that
there is consistancy across nodes which have statistics
enabled or disabled
Fixes #248
> falter-berlin-migration: finish migration for 1.2.0

- luci/luci-app-falter-owm/files/owm.sh
There was some little word missing in owm.sh. In result, the
uptime was not included right into the json-string. On the map
nodes with the old version of the script show constantly an up-
time of just a few seconds.
Description:
> luci-app-falter-owm: Fix uptime in owm.sh

- luci/luci-app-ffwizard-falter/Makefile
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
- luci/luci-mod-falter/Makefile
- luci/luci-mod-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua
Due to inconsistancies in the lua script, both fields mode_radioN and meshmode_radioN were being used.  This fixes this to use only meshmode_radioN
> Meshmode pages - fix field names to be consistant

- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
Ensure that /etc/profile.d/dynbanner.sh is removed
Ensure that the ubus.sock is defined correctly in rpcd
Remove unneeded mode_radioN options in ffwizard
Remove ff_olsr_watchdog script from crontab
Fixes: #264
> falter-berlin-migration: migration for 1.2.1

- luci/luci-app-falter-owm/Makefile
- luci/luci-app-falter-owm/files/owm.sh
This applies several tips from the shellcheck tool. There
was one bug fixed (empty field for owm-api) and several
possibilities for potential word-globbing-issues.
Run tested: GL-AR150
> luci-app-falter-owm: apply shellcheck tips

- luci/luci-app-falter-owm/Makefile
- luci/luci-app-falter-owm/files/owm.sh
Do not add interfaces with "wg_" in the name.
> luci-app-falter-owm: exclude wireguard interfaces

- packages/falter-berlin-tunnelmanager/files/tunnelman.sh
Should fix #280.
5 seconds seem to be to fast to register an interface. I suspect that
the client registers some interface, a timeout triggers, and the server
installed the interface. However, due to the timeout, the client excepts
that a failure occurs. That continues in a loop and will prevent a
client to connect to some gateway again. Increase timeout to 1 minute to
allow the client to have enough time to install the wireguard interface.
> falter-berlin-tunnelmanager: increase timeout to register interface

- packages/falter-berlin-tunnelmanager/Makefile
- packages/falter-berlin-tunnelmanager/files/tunnelman.sh
- packages/falter-berlin-tunnelmanager/files/tunnelmanager.config
- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Define mtu in the config that should be used in for the tunnel.
Sometimes you only have ppoe, however sometimes people have 4in6 and so
on. Different setups need different MTUs.
> falter-berlin-tunnelmanager: add option for mtu

- packages/falter-berlin-autoupdate/files/autoupdate.sh
- packages/falter-berlin-autoupdate/files/lib_autoupdate.sh
- packages/falter-berlin-autoupdate/files/post-inst.sh
This adds some further checks. For example, nodes with development
firmware shouldn't perfom an auto-update.
> falter-berlin-autoupdate: add some checks and refinements

- packages/falter-berlin-autoupdate/files/autoupdate.sh
- packages/falter-berlin-autoupdate/files/post-inst.sh
There was an error in the random-stuff which resulted in that sometimes
the initialisation of the random update-time failed.
Aditionally also exclude rc-candidates by using regex.
Please cherry-pick to `Openwrt-21.02-branch` too.
> falter-berlin-autoupdate: minor fixes

- packages/falter-berlin-autoupdate/files/post-inst.sh
Add test in crontab to call autoupdate only, if the script exists.
> falter-berlin-autoupdate: only call autoupdate if it exists

- packages/falter-berlin-tunnelmanager/files/up.sh
If a configured ip matches a part of an available it results in this:
echo 10.22.112.16 | sed "s/10.22.112.1//"
-> 6
and the ip 6.0.0.0/32 will be assigned.
> falter-berlin-tunnelmanager: fix available ips calculation

- packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
- packages/falter-berlin-uhttpd-defaults/uci-defaults/freifunk-berlin-uhttpd-defaults
Enables https-redirection for LuCI-Admin-Interface and handles mifration too.
Please cherry-pick into just 21.02
Description:
> Feature/activate https for LuCI-Admin-interface

- packages/falter-berlin-autoupdate/doc/falter-berlin-autoupdate.rst
A friendly community member spotted some spelling errors in
the README, which get corrected by this.
> falter-berlin-autoupdate: fix some typos in README

- luci/luci-mod-falter/luasrc/view/freifunk/index.htm
A fellow Freifunka spotted an typing issue in the welcome-page,
which should be fixed with this.
https://lists.berlin.freifunk.net/pipermail/berlin/2022-May/053051.html
> luci-mod-falter: fix Typo in index-page

- packages/falter-berlin-firewall-defaults/Makefile
OpenWrt-22.03 will use firewall4 for firewall configuration. According
to the release notes, there should be no difference in th uci configuratiuon
files, so that old defaults should still work.
https://openwrt.org/releases/22.03/notes-22.03.0-rc1#firewall4_based_on_nftables
> falter-berlin-firewall-defaults: migrating to fw4

- .gitignore
The .vscode directories should be ignored.
> gitignore: Add vscode-rule

- packages/falter-berlin-ssid-changer/files/hotplug.d/30-ssid-changer
- packages/falter-berlin-ssid-changer/files/lib/lib_ssid-changer.sh
Instead of hardcoding the dns servers of big dns providers, we should use
the dns servers configured for checking internet connectivity.
This prevents the case, where clients can't reach the internet, as these
servers are not reachable, but the big servers are.
Applies some shellcheck-issues additionally.
Fixes #309
> falter-berlin-ssid-changer: use dns server from config

- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Maintainer: @PolynomialDivision 
Compile tested: -
Run tested: 22.03-snapshot @ firecracker x86-64
Description:
We want a working tunnel as fast as possible, but 95 is pretty late in the boot process. network is at 20 and olsrd/babel at 65/70, so 40 should be fine.
Also stop a little later - tunnelmanager doesn't need to be among the first services that are stopped.
Reduces time-to-tunnel in a VM from 1m20s to 15s
> tunnelmanager: start it earlier

- packages/athwatch/Makefile
- packages/athwatch/files/athwatch.init
Maintainer: me
Compile tested: EAP225-Outdoor, OpenWrt 22.03-SNAPSHOT
Run tested: EAP225-Outdoor, OpenWrt 22.03-SNAPSHOT
Description:
An attempt at a workaround for freifunk-berlin/bbb-configs#117 - tails `logread` for any occurence of "failed to send pdev bss" and then reboots. Unforunately it looks like a simple rmmod/modprobe cycle can throw the driver and firmware completely off the rails...
> athwatch: add watchdog for ath10k wifi bug

- packages/falter-berlin-tunnelmanager/files/tunnelman.sh
- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Maintainer: @PolynomialDivision 
Compile tested: ipq40xx
Run tested: ipq40xx
Description:
It turns out that START=40 is a little too early, often times netifd hasn't brought up all interfaces yet. As a result, we can't create the macvlan sub-interface of br-uplink yet and tunnelman.sh aborts. START=55 is better, but ideally we'd give some option to procd to wait for the network to be ready.
The early abort mentioned above led to an unreconverable state because the network namespace was left behind. There might be more spots for cleanup, but these two here already help.
With this cleanup, the too-early startup mentioned above is not a big deal anymore, since procd will simply try restarting tunnelman.sh after a short while.
> Two small tunnelmanager fixes

- fetch_translation_tools.sh
With the new repo-builder-script, build-dir will hold some other scripts, which we want to keep. Adjust translation fetcher to take care of that.
This commit depends on #338
> fetch_translation_tools.sh: adjust translation tool downloader

- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/generalInfo.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/optionalConfigs.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/shareInternet.lua
- luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/decide.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/reboot.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/enableStats.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/generalInfo.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/ipinfo.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/meshipinfo.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/shareBandwidth.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/vpncertreupload.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/vpninfo.htm
- luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/snippets/welcome.htm
- luci/luci-app-ffwizard-falter/po/de/ffwizard-falter.po
- luci/luci-app-ffwizard-falter/po/en/ffwizard-falter.po
- luci/luci-app-ffwizard-falter/po/templates/ffwizard-falter.pot
LuCI doesn't provide English translation packages anymore and
assumes, that English is the base language. Thus changing.
fixes #246
> Change wizard base-lang to english

- packages/falter-berlin-ssid-changer/Makefile
- packages/falter-berlin-ssid-changer/files/hotplug.d/30-ssid-changer
- packages/falter-berlin-ssid-changer/files/post-inst.sh
In the merged state before, the ssid-changer was only functional, if there did happen a change in the state of interfaces. But if a router started without having internet connectivity, it wasn't working at all.
This commit adds a check for connectivity running every 5 minutes, hopefully increasing the user experience a lot.
> falter-berlin-ssid-changer: several fixes

- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Wait for mesh daemons running before starting tunnelmanager.
> falter-berlin-tunnelmanager: wait for mesh daemons to be started

- .github/workflows/shellcheck-lint.yml
This adds ShellCheck to the repository, but ignores the files with issues for now. The idea is to prevent ShellCheck errors in new code, but allow old code to be fixed over time.
> workflows: add ShellCheck and ignore existing files with issues

- luci/luci-app-falter-service-registrar/Makefile
- luci/luci-app-falter-service-registrar/htdocs/luci-static/resources/view/falter-service-registrar/form.js
- luci/luci-app-falter-service-registrar/po/de/service-registrar.po
- luci/luci-app-falter-service-registrar/po/templates/service-registrar.pot
- luci/luci-app-falter-service-registrar/root/usr/share/luci/menu.d/luci-app-falter-service-registrar.json
- luci/luci-app-falter-service-registrar/root/usr/share/rpcd/acl.d/luci-app-falter-service-registrar.json
- packages/falter-berlin-service-registrar/LICENSE
- packages/falter-berlin-service-registrar/Makefile
- packages/falter-berlin-service-registrar/README.rst
- packages/falter-berlin-service-registrar/doc/falter-berlin-service-registrar.rst
- packages/falter-berlin-service-registrar/files/ffserviced.sh
- packages/falter-berlin-service-registrar/files/ffservices.conf
- packages/falter-berlin-service-registrar/files/register-services.sh
website-registrar is a tool meant to automatise the registration of services in the freifunk-berlin-network. Its in an early draft-state. Currently it supports registering a website wich is hosted in routers `/tmp/`-directory and gets delivered by OpenWrts uhttpd webserver.
> Add service registrar

- .github/workflows/shellcheck-lint.yml
Add two more exceptions as we missed to properly rebase the PR before merging which would have avoided the merge.
> workflows: add two more scripts as shellcheck exceptions

- .github/workflows/formal.yml
- .github/workflows/multi-arch-test-build.yml
- .github/workflows/shellcheck-lint.yml
- .github/workflows/yaml-lint.yml
switch to v3 because v2 is deprecated
> workflows: update checkout action to v3

- CONTRIBUTING.md
- packages/falter-berlin-admin-keys/Makefile
- packages/falter-berlin-autoupdate/Makefile
- packages/falter-berlin-bbbdigger/Makefile
- packages/falter-berlin-dhcp-defaults/Makefile
- packages/falter-berlin-freifunk-defaults/Makefile
- packages/falter-berlin-lib-guard/Makefile
- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-network-defaults/Makefile
- packages/falter-berlin-olsrd-defaults/Makefile
- packages/falter-berlin-service-registrar/Makefile
- packages/falter-berlin-ssid-changer/Makefile
- packages/falter-berlin-statistics-defaults/Makefile
- packages/falter-berlin-system-defaults/Makefile
- packages/falter-berlin-tunnelmanager/Makefile
- packages/falter-berlin-uhttpd-defaults/Makefile
This pull request replaces all `github.com/Freifunk-Spalter/packages` urls by `github.com/freifunk-berlin/falter-packages`.
> Makefiles: update falter-package url

- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Maintainer: @PolynomialDivision 
Compile tested: x86_64 snapshot
Run tested: x86_64 snapshot
Description:
With START=55 it started before babeld and olsrd, blocking them from starting. It then unsuccessfully waited for them to come up.
With START=70, olsrd will already have started and babeld will start the same time in parallel. This way tunnelmanager can't block them, and can actually finish waiting quickly.
> tunnelmanager: give babel and olsr a chance to start before waiting for them

- build/build.sh
Maintainer: 
Compile tested: n/a
Run tested: yes
Description:
- build.sh now has a nice help text showing available branch and arch values
- destination argument is now optional, defaults to `./out/<branch>/<arch>`
- documented Podman command has been updated
```
> ./build/build.sh
usage: build/build.sh <branch> <arch> [<destination>]
branch names:
master  openwrt-22.03  openwrt-21.02
arch names:
run build/build.sh with a branch name to see available arch names
destination:
path to a writable directory where the 'falter' feed directory will end up.
default: ./out/<branch>/<arch>
```
```
> ./build/build.sh foo
usage: build/build.sh <branch> <arch> [<destination>]
branch name:
foo
arch names:
cat: build/targets-foo.txt: No such file or directory
destination:
path to a writable directory …
```
> build: improve UX a little

- packages/falter-berlin-autoupdate/LICENSE
- packages/falter-berlin-autoupdate/Makefile
- packages/falter-berlin-autoupdate/files/autoupdate.sh
- packages/falter-berlin-autoupdate/files/lib_autoupdate.sh
- packages/falter-berlin-autoupdate/files/post-inst.sh
When there was no board-json on the firmware selector autoupdate responded with a too generic error message. Thus we get more specific here.
Fixes #376
Please cherry-pick -x to 22.03 and 21.02
> falter-berlin-autoupdate: Add error prompt for board-json

- packages/falter-berlin-migration/Makefile
- packages/falter-berlin-uplink-notunnel/Makefile
- packages/falter-berlin-uplink-tunnelberlin/Makefile
Maintainer: 
Compile tested: x86_64
Run tested: x86_64
Description:
Three oopsies that I missed in #384 :-(
These result in the following errors from opkg:
```
Collected errors:
* pkg_hash_check_unresolved: cannot find dependency falter-berlin-lib-guard for falter-berlin-migration
* pkg_hash_fetch_best_installation_candidate: Packages for falter-berlin-migration found, but incompatible with the architectures configured
* opkg_install_cmd: Cannot install package falter-berlin-migration.
* pkg_hash_check_unresolved: cannot find dependency falter-berlin-lib-guard for falter-berlin-uplink-tunnelberlin
* pkg_hash_check_unresolved: cannot find dependency falter-berlin-network-defaults for falter-berlin-uplink-tunnelberlin
* pkg_hash_fetch_best_installation_candidate: Packages for …
```
> packages: fix a few dependencies oopsies

- packages/falter-common/Makefile
Maintainer: 
Compile tested: master x86_64, master aarch64_generic
Run tested: not yet
Description:
Creates falter-standard, falter-notunnel, falter-backbone packages to replace builter's packagesets. On builter's side, the snapshot packagesets will only contain a single package, and eventually can be removed.
The falter-common package now pulls in everything that's needed falter-backbone, and the new falter-more package pulls in everything needed for falter-standard and falter-notunnel.
Needs testing.
> packages: convert builter packagesets to proper meta packages

- packages/falter-common/files/etc/uci-defaults/freifunk
- packages/falter-common/files/etc/uci-defaults/freifunk-berlin-pingcheck-defaults
- packages/falter-common/files/etc/uci-defaults/freifunk-berlin-uhttpd-defaults
- packages/falter-common/files/etc/uci-defaults/freifunk-berlin-wireless-defaults
- packages/falter-common/files/etc/uci-defaults/freifunk-olsrv1
Description:
- Remove redundant freifunk-olsrv1 script
- Remove freifunk script, move its contents to uhttpd
- Add guards for network, pingcheck, wireless
Now that most uci-defaults script have moved into the falter-common package, bbb-configs needs to be able to disable all of them. That's what the added guards are for.
> packages: clean up uci-defaults, add missing guards

- packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
Maintainer: @PolynomialDivision 
Compile tested: openwrt-23.05
Run tested: openwrt-23.05 / ipq40xx / fritzbox-4040
Description:
This was a double hardcoding :-)
Tunnel endpoint configuration is helpful for debugging connectivity problems such as freifunk-berlin/bbb-configs#493
> tunnelmanager: fix tunnel endpoint configuration

- packages/falter-berlin-tunnelmanager/files/tunnelman.sh
This introduces an additional delay which allows for used keys to time out on the servers. Without this tunnelmanager could end up in an endless loop where it keeps the keys in a used state and never completes to establish a tunnel.
> tunnelmanager: allow used keys to time out on servers

- packages/falter-berlin-tunnelmanager/files/up.sh
After creating new tunnels the ipc calls are often unreliably and olsrd even crashes in combination with using ipc, which results in unconfigured interfaces. The problem is that the current ipc code simply does not have any error handling to deal with failed calls. This change switches back to reloading olsrd and babeld to make tunnels more reliably in order to prevent nodes from getting isolated, but reintroduces the issue of loosing routes when doing a reload. A solution to this is pointed out here: https://github.com/freifunk-berlin/falter-packages/issues/401#issuecomment-1689911339
For reference a log that shows olsrd crashing with ipc.
```
Mon Sep 11 15:19:38 2023 user.notice tunnelman: Server handling least clients is: 77.87.51.131. Trying to create tunnel...
Mon Sep 11 15:19:40 …
```
> tunnelmanager: fix adding interfaces by reloading again

- packages/ucode-mod-ctypes/Makefile
- packages/ucode-mod-ctypes/src/ctypes.c
- packages/ucode-mod-wireguard/Makefile
- packages/ucode-mod-wireguard/src/wireguard.c
Maintainer: me / @pktpls
Compile tested: x86_64
Run tested: x86_64
Description:
ucode-mod-ctypes is an extraction from [jow-/ucode#121](https://github.com/jow-/ucode/pull/121) which seems to have lost momentum. It'll allow us to call into C libraries such as libuclient, libdht, libusign, etc.
ucode-mod-wireguard has been copied from ucode-mod-nl80211 and adapted for the two Wireguard netlink commands WG_CMD_GET_DEVICE and WG_CMD_SET_DEVICE. I'll discuss with Jow how to generalize the repeating netlink modules in the future.
> packages: add ucode-mod-ctypes and ucode-mod-wireguard

- luci/luci-app-falter-owm/files/owm.sh
- packages/tunspace/Makefile
- packages/tunspace/tunspace.defaults
- packages/tunspace/tunspace.init
- packages/tunspace/tunspace.uc
- packages/ucode-mod-wireguard/Makefile
Maintainer: @pktpls
Compile tested: all - testbuildbot branch based on openwrt-23.05
Run tested: bbb-configs VM (x86_64), Zyxel NWA50AX (mipsel_24kc), TP-Link EAP225-Outdoor (mips_24kc)
Description:
New attempt at wireguard tunnel client. Uses the existing gateway servers and their registration mechanism. Important differences to Tunnelmanager:
- Everything is contained in one [ucode](https://ucode.mein.io) file
- The uplink namespace does DHCP to get an IP address and default route, no need for explicit IP configuration anymore.
- Server selection is randomized, not picking the server with the lowest number of clients anymore. This has occasionally led to situations where we connected to the same broken server again and again.
- Tunnel interfaces (`ts_wg0`, `ts_wg1`, etc.) are created …
> packages: add initial version of tunspace

- .github/workflows/linter.yml
Disable the linter as it has problems with the syntax of LuCi JavaScript Apps
> workflows: disable JS standard style linter

- luci/luci-app-falter-autoupdate/htdocs/luci-static/resources/view/falter-autoupdate/form.js
Adds validator to the input fileds of the autoupdate luci app. Runtested on my falter router at home.
> falter-berlin-autoupdate: Add validators to input fields

- packages/falter-berlin-autoupdate/files/autoupdate.sh
Option `-N` will override the uptime-check.
> falter-berlin-autoupdate: Add Now-Option

- fetch_translation_tools.sh
This commit fixes some shellcheck issues in the mentioned script. It precedes #315.
> fetch_translation_tools.sh: fix shellcheck issues

- packages/falter-common/files/etc/uci-defaults/freifunk-berlin-network-defaults
Compile tested: No.
Run tested: No.
`dhcp6` is not a valid protocol. It should be `dhcpv6`. This fixes the error `Unsupported protocol type.` in LuCi.
> Fix typo (dhcp6 -> dhcpv6)

- packages/tunspace/tunspace.defaults
- packages/tunspace/tunspace.init
- packages/tunspace/tunspace.uc
Compile tested: ipq40xx, ath79
Run tested: Fritzbox 4040, Glinet GL-XE300
These changes came about while setting up the XE300's internal LTE modem.
- Handling of the uplink interface in various difficult situations is now much more robust, it recovers more reliably, etc.
- Some types of uplink interfaces can't be added to a bridge, for various reasons. We now support a "direct" uplink mode which doesn't clone a macvlan bridge interface, and instead moves the uplink interface itself directly to the namespace.
- The downside of this mode is that the fully configured and functional uplink interface will definitely leak out of the namespace on tunspace restart or stop.
- The wg-installer servers on each gateway have a timeout based on a client's private key, which …
> tunspace: bunch of improvements

- packages/tunspace/tunspace.uc
Compile tested: yes snapshot
Run tested: x86/64 snapshot
Our DHCP requests to the uplink DHCP server don't specify an existing IP address that we might already have. Most DHCP servers will notice that and give us the existing IP adress. A few DHCP servers will give us a fresh new different IP address for every maintenance tick, and quickly exhaust their IP pool depending on the leasetime.
I'm too lazy to completely handle leasetimes, so a good middleground is to tell the DHCP server that we already have an address and would like to renew it.
It looks like this in action:
```
tick
rtnl: cmd=18 flags=1 msg={ "ifname": "ts_uplink" } error=null reply=bool
ip -n uplink link show ts_uplink >/dev/null 2>/dev/null (exit=0)
ip -n uplink link set ts_uplink up (exit=0) …
```
> tunspace: avoid exhausting uplink's DHCP IP pool

- packages/falter-common/Makefile
Compile tested: x86_64 snapshot
Run tested: yes x86/64 VM, german translation okay on http://localhost:8080/cgi-bin/luci/admin/system/package-manager
See https://github.com/openwrt/luci/commit/bcd13b918e2f30b8d19027a06e3d773a1b0ec4c0
> falter-common: opkg packages renamed to package-manager

- packages/falter-berlin-autoupdate/files/autoupdate.sh
- packages/falter-berlin-autoupdate/files/lib_autoupdate.sh
The option `--ignore-minor-compat-version` enables the sysupgrade command to do an update also in case, there is a minor compat-version upgrade. This is relevant for the change from swconfig to dsa.
Compile tested: no.
Run tested: Yes, on a Archer-C5v1 w/ Falter 1.2.3 (OpenWrt-21.02) and mikrotik_routerboard-750gr3 w/ OpenWrt-23.05
> falter-berlin-autoupdate: if possible, use --ignore-minor-compat-version

- build/build.sh
Kompiliert Ja/Nein: x86_64 snapshot
Läuft live Ja/Nein: x86_64 snapshot
Beschreibung deiner Änderungen:
AI scrapers are hammering git.openwrt.org to overload, which occasionally lets our builds fail.
> build: switch to github.com repos

- packages/bird2-babelpatch/Makefile
An assembler instruction "vst1.8 {d16-d17}, [r0 :64]" requires `r0` to be 64-bit (8-byte) aligned. However, in certain cases, `r0` was not aligned, leading to a SIGBUS error on ARMv7 platforms:
kern.err kernel: [90636.175853] Alignment trap: not handling
instruction f4400a1f at [<00056fbc>]
kern.alert kernel: [90636.182044] Unhandled fault: alignment
exception (0x801) at 0xb6dec01c
A backtrace shows the crash occurring in `bgp_get_prefix` due to the misaligned memory address.
Fix this issue by passing the `-mno-unaligned-access` flag to GCC/Clang. This ensures unaligned accesses are avoided on platforms like ARMv7, preventing alignment-related exceptions and ensuring reliable execution.
> bird2-babelpatch: fix unaligned access on ARMv7 targets

- packages/bird2-babelpatch/Makefile
An assembler instruction "vst1.8 {d16-d17}, [r0 :64]" requires `r0` to be 64-bit (8-byte) aligned. However, in certain cases, `r0` was not aligned, leading to a SIGBUS error on ARMv7 platforms:
kern.err kernel: [90636.175853] Alignment trap: not handling
instruction f4400a1f at [<00056fbc>]
kern.alert kernel: [90636.182044] Unhandled fault: alignment
exception (0x801) at 0xb6dec01c
A backtrace shows the crash occurring in `bgp_get_prefix` due to the misaligned memory address.
Fix this issue by passing the `-mno-unaligned-access` flag to GCC/Clang. This ensures unaligned accesses are avoided on platforms like ARMv7, preventing alignment-related exceptions and ensuring reliable execution.
(cherry picked from commit fcce390fc57b44593fe969f1063c6ba711fc7f9b)
> [24.10] bird2-babelpatch: fix unaligned access on ARMv7 targets

- packages/bird2-babelpatch/Makefile
An assembler instruction "vst1.8 {d16-d17}, [r0 :64]" requires `r0` to be 64-bit (8-byte) aligned. However, in certain cases, `r0` was not aligned, leading to a SIGBUS error on ARMv7 platforms:
kern.err kernel: [90636.175853] Alignment trap: not handling
instruction f4400a1f at [<00056fbc>]
kern.alert kernel: [90636.182044] Unhandled fault: alignment
exception (0x801) at 0xb6dec01c
A backtrace shows the crash occurring in `bgp_get_prefix` due to the misaligned memory address.
Fix this issue by passing the `-mno-unaligned-access` flag to GCC/Clang. This ensures unaligned accesses are avoided on platforms like ARMv7, preventing alignment-related exceptions and ensuring reliable execution.
(cherry picked from commit fcce390fc57b44593fe969f1063c6ba711fc7f9b)
> [23.05] bird2-babelpatch: fix unaligned access on ARMv7 targets

- packages/tunspace/tunspace.init
- packages/tunspace/tunspace.uc
Compile tested: x86_64 snapshot
Run tested: x86_64 snapshot bbb-configs
We currently don't have the wireguard server (wg-installer-server) installed on ak36-gw and strom-gw. This exposes two bugs in tunspace:
1. It doesn't properly deal with the wireguard server host and http server being available, while the specific wg-installer-server http endpoint is missing. Instead it just crashes.
2. The procd service script doesn't set custom respawn options, and the defaults would only respawn after an hour.
> tunspace: handle http endpoint quirks, fix respawn behavior

- packages/bgpdisco/Makefile
- packages/bgpdisco/bird_config_template.ut
Typical route as readvertised from saarbruecker (working):
```
2001:bf7:760:10fc::1/128 unreachable [bgpdisco_1_eth4_12 2024-12-24 from fe80::f29f:c2ff:fe0f:793d] * (100) [i]
Type: BGP univ
BGP.origin: IGP
BGP.as_path: 
BGP.next_hop: 2001:db8:: fe80::f29f:c2ff:fe0f:793d
BGP.local_pref: 100
BGP.fa [t]: 5b 20 5b 20 30 2c 20 22 73 77 69 74 63 68 30 5f 31 30 34 2e 73 65 67 65 6e 2d 63 6f 72 65 22 20 5d 20 5d
```
Local route advertised from static protocol (non-working)
```
bird> show route 2001:bf7:760:2201::2/128 all export bgpdisco_9_gre4_ak36 
Table v6_bgpdisco:
2001:bf7:760:2201::2/128 blackhole [static_bgpdisco_v6 2024-12-18] * (200)
Type: static univ
BGP.fa [t]: 5b 20 5b 20 30 2c 20 22 67 72 65 34 2d 6c 31 30 35 2e 73 61 61 72 62 72 75 65 63 6b 65 72 2d 67 77 22 20 5d 20 5d
```
See …
> bgpdisco: fixup advertisement of static routes

- luci/luci-mod-falter/luasrc/view/freifunk/public_status.htm
Compile tested: yes (snapshot)
Run tested: yes
see here for reference https://github.com/openwrt/luci/pull/739
```
Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: /usr/lib/lua/luci/template.lua:181: Failed to execute template 'freifunk/public_status'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/freifunk/public_stat..."]:116: attempt to index field 'iwdata' (a nil value)
```
> Luci-Mod-Falter (public status): iwdata can be nil

- build/build.sh
- packages/tunspace/Makefile
- packages/tunspace/tunspace.defaults
- packages/tunspace/tunspace.uc
Compile tested: x86_64, snapshot
Run tested: x86/64, snapshot, tunspace works with both static IP and DHCP, logspam is prevented
More info in the commit messages. Fixes #467 
The `build:` commit is unrelated and helps us build images with a custom package feed locally.
> tunspace: static IP support, log spam prevention

- build/build.sh
Kompiliert Ja/Nein: alle
Läuft live Ja/Nein: alle
Beschreibung deiner Änderungen:
Clean up the existing mirror code, and let us select a mirror using the `FALTER_MIRROR` env var. There are three variants of repositories.conf:
- git.openwrt.org is the standard
- github.com has custom paths (flattened into the openwrt org)
- other mirrors likely don't have Git-smart support, so we use `src-full` there. (This applies to mirror.freifunk.dev)
> build: add FALTER_MIRROR env var

- packages/falter-berlin-tunneldigger/Makefile
Compile tested: x86_64
Run tested: n/a
Not sure if this has been wrong the whole time, but since openwrt/openwrt@042996b46bd41292ef1fa2d58e3b824a547f4c55 it actually fails the build.
No backports needed at the moment.
> tunneldigger: fix PKG_MIRROR_HASH
