freifunk-berlin/falter-packages

.circleci/Dockerfile
.circleci/README
.circleci/config.yml

Just copied https://github.com/openwrt/packages/tree/master/.circleci and removed the "real name" part.
Add checks for
- signed-off
- "package-name: description"
- build check
- ...

circleci: add circleci from openwrt packages community feed

---

luci/luci-app-olsr2/Makefile
luci/luci-app-olsr2/luasrc/controller/olsr2.lua
luci/luci-app-olsr2/luasrc/tools/olsr2.lua
luci/luci-app-olsr2/luasrc/view/status-olsr2/common_js.htm
luci/luci-app-olsr2/luasrc/view/status-olsr2/error_olsr.htm
luci/luci-app-olsr2/luasrc/view/status-olsr2/interfaces.htm
luci/luci-app-olsr2/luasrc/view/status-olsr2/legend.htm
luci/luci-app-olsr2/luasrc/view/status-olsr2/neighbors.htm
luci/luci-app-olsr2/luasrc/view/status-olsr2/overview.htm
luci/luci-app-olsr2/root/etc/config/luci_olsr2
luci/luci-app-olsr2/root/etc/uci-defaults/40_luci-olsr2
luci/luci-app-olsr2/root/usr/share/rpcd/acl.d/luci-app-olsr2.json

Jakob from Funkfeuer Wien has adapted the luci-app-olsr plugin to the new olsrv2 version. We also want to expriment with it, so I add it to the feed.
The original code can be found here:
https://git.chaosfield.at/jakob/luci-olsrd2

luci-app-olsr2: add early package version

---

luci/luci-app-ffwizard-falter/luasrc/controller/assistent/assistent.lua

Make those annoying tabs in the wizard dissapear.
Fixes: #8

master: luci-app-ffwizard-flaster: remove tabs

---

luci/luci-app-ffwizard-falter/luasrc/controller/assistent/assistent.lua

Make those annoying tabs in the wizard dissapear.
Cherry-picked from baa659c35ac5266fd22ab91b41be19c097480623
Fixes: #8

Openwrt-1907: luci-app-ffwizard-flaster: remove tabs

---

luci/luci-app-falter-owm/luasrc/owm.lua

For some reason, which I'm not really sure how it happened,
not all the desired changes made it into commit a5292ad.  Here
are the rest of the desired changes.
Please cherry-pick into the 19.07 branch.

luci-app-falter-owm: fix commit a5292ad

---

README.md

This commit tests the webhook to falter buildbot-master.
If we merge something, buildbot should start to build the
new version of the feed automatically.
Buildbot should start building after 5 Minutes.

TESTCOMMIT: testing webhook to buildbot

---

luci/luci-mod-falter/luasrc/view/cbi/osmll_value.htm

This is based on a commit submitted by @andibraeu
https://github.com/freifunk/openwrt-packages/pull/36/commits/32b6f441dcef892a65feea4804e6122274fd362f
Fixes: #34

luci-mod-falter: fix the map in basic settings

---

packages/falter-common/Makefile
packages/falter-policyrouting/Makefile

use PKGARCH:=all for packages which could use it
Fixes: #137

Pkgarch all

---

packages/falter-common/Makefile

falter-common: use git tag for FREIFUNK_REVISION is possible

---

luci/luci-app-ffwizard-falter/Makefile
luci/luci-mod-falter/Makefile

With commit 9fd6eda the pkgver was not increased.

luci-mod-freifunk: luci-app-ffwizard-falter: bump pkgver

---

luci/luci-app-ffwizard-falter/Makefile
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
luci/luci-app-ffwizard-falter/luasrc/tools/freifunk/assistent/tools.lua
luci/luci-mod-falter/Makefile
luci/luci-mod-falter/luasrc/model/cbi/freifunk/bbbdigger.lua
packages/falter-berlin-bbbdigger/Makefile
packages/falter-berlin-bbbdigger/files/postinst.sh
packages/falter-berlin-dhcp-defaults/Makefile
packages/falter-berlin-dhcp-defaults/uci-defaults/freifunk-berlin-dhcp-defaults
packages/falter-berlin-firewall-defaults/Makefile
packages/falter-berlin-firewall-defaults/uci-defaults/freifunk-berlin-firewall-defaults
packages/falter-berlin-network-defaults/Makefile
packages/falter-berlin-network-defaults/lib/functions/freifunk-berlin-network.sh
packages/falter-berlin-network-defaults/uci-defaults/freifunk-berlin-network-defaults
packages/falter-berlin-uplink-notunnel/Makefile
packages/falter-berlin-uplink-notunnel/uci-defaults/freifunk-berlin-z95_notunnel

This set of commits are needed to have a properly working firstboot and to have a successful run on the wizard.  Also, the freifunk-berlin-bbbdigger package was updated.

Changes needed for 2102

---

packages/falter-berlin-olsrd-defaults/Makefile
packages/falter-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults

falter-berlin-olsrd-defaults: 21.02 set procd parameters

---

luci/luci-mod-falter/Makefile
luci/luci-mod-falter/luasrc/model/cbi/freifunk/bbbdigger.lua
packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

Fix a typo
Bug introduced in 9ab7a8595ec24315de2112ffed439797a16d934b

luci-mod-falter: fix typo for bbbdigger page

---

luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
luci/luci-mod-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua

Rewrite the text blocks which need to be translated so that they work properly with the il18n system.
The actual translations to german still need to be done.
Fixes: #175

2102 fix translations

---

luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua
luci/luci-mod-falter/luasrc/model/cbi/freifunk/swapports.lua

The new Freifunk Menu item will swap the WAN ports and the DHCP ports
on the router.

luci-mod-falter: add swapports page

---

luci/luci-app-falter-owm/luasrc/controller/antennas.lua
luci/luci-app-falter-owm/luasrc/model/cbi/antennas.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/changePassword.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/generalInfo.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/optionalConfigs.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/shareInternet.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/assistent/wireless.lua
luci/luci-app-ffwizard-falter/luasrc/model/cbi/freifunk/upgrades/005-wireless-mesh.lua
luci/luci-app-ffwizard-falter/luasrc/view/freifunk/assistent/decide.htm
luci/luci-mod-falter/luasrc/model/cbi/freifunk/wireless-mesh.lua

There are some missing translations, especially to english.  The changes here a the preparations needed for the translations to be finished.
Please, take a close look at the code to make sure everything is called correctly.
If/when this PR gets merged, please create an issue which mentions this PR and that the actual translations are still needed.
Please cherry-pick into 21.02

[RFC][WIP] Finish translations

---

README.md

Changed to freifunk-berlin/falter-*
Description:

README.md: Change repo to new location

---

packages/falter-berlin-tunnelmanager/Makefile
packages/falter-berlin-tunnelmanager/files/down.sh
packages/falter-berlin-tunnelmanager/files/tunnelman.sh
packages/falter-berlin-tunnelmanager/files/tunnelmanager.init
packages/falter-berlin-tunnelmanager/files/up.sh

falter-berlin-tunnelmanager: several fixes

---

luci/luci-app-ffwizard-falter/luasrc/tools/freifunk/assistent/tools.lua

On some device we arbitrarily experienced some issues with getting nil-
values from a rpc-call. This call figures out if there was a root password
set already. As nil-values crash the LuCI-Interface, we provide an
alternative value if the call returns nil, which is assuming that the
password was not set.
Fixes #298

luci-app-ffwizard-falter: fix nil-error

---

luci/luci-app-falter-owm/files/owm.sh

For serveral sites we don't have only one maintainer, but several one. Thus we should also have the possibility to give more than only one contact option, which is enabled with this commit.
In `/etc/config/freifunk` we can now give contacts in this way:
```uci
config public 'contact'
option nickname 'akira25'
// old style:
// option mail 'https://config.berlin.freifunk.net/contact/42/InNwYW5kYXVlcmRhbW0xMzQi.FMHyiw.1LVt'
// new style:
list contact 'contact 1'
list contact 'https://config.berlin.freifunk.net/contact/42/InNwYW5kYXVlcmRhbW0xMzQi.FMHyiw.1LVt'
list contact 'info@example.com'
list contact 'https://link-to-matrix-room.to'
option location 'somewhere in Berlin
```
owm.sh will work with both styles, old and new one.

luci-app-falter-owm: introduce option-list for contacts

---

packages/falter-berlin-migration/files/lib/functions/semver.sh
packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

Add Migration script for 1.2.3-release.
This closes #303, #300 and #331

Add migration 1.2.3

---

luci/luci-app-falter-owm/files/owm-defaults
packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

The hopglass map updates twice every hour. This change reflects this and introduces more frequent updates.

OWM: update twice every hour

---

.config/yaml-lint.yml
.github/workflows/formal.yml
.github/workflows/multi-arch-test-build.yml
.github/workflows/yaml-lint.yml

This fixes existing yaml-lint issues and enables yaml-lint for the repo to increase code quality in the future.

workflows: fix yaml-lint issues and enable yaml-lint for the repo

---

.github/workflows/shellcheck-lint.yml
packages/falter-berlin-migration/files/lib/functions/semver.sh
packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

There are some bashisms in the migration-script, which should be fixed. This is rather low priority, as it works.

migration: fix bashism

---

packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh
packages/falter-policyrouting/files/etc/uci-defaults/freifunk-policyrouting

This should fix #350.
I tested the function on a live system already, but we should look out for a full blown test with the rc-release.

Fix 350: Multiple uci-tracks

---

packages/falter-common/files-common/etc/uci-defaults/freifunk-berlin-ffwizard3-json
packages/falter-common/files-common/lib/upgrade/keep.d/ffwizard3
packages/falter-common/files-common/sbin/ffwizard2uci
packages/falter-common/files-common/sbin/uci2ffwizard

These scripts can translate an uci-configuration to a freifunk-configuration-json and vice versa.

falter-common: add ffwizard3-scripts

---

packages/falter-berlin-freifunk-defaults/uci-defaults/freifunk-berlin-freifunk-defaults
packages/falter-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

write freifunk-file from uci-default-script, to preserve contact information. Related to #368

Fix upgrade

---

packages/falter-common/Makefile
packages/falter-common/files-common/usr/bin/ffdzero
packages/falter-common/files/etc/init.d/freifunk
packages/falter-common/files/etc/profile.d/10_dynbanner.sh

Apply shellcheck-fixes for the dynbanner-script and some more.

falter-common: Apply shellcheck-fixes and add License-note

---

packages/falter-berlin-autoupdate/doc/falter-berlin-autoupdate.rst

Please cherry-pick to 22.03 and 21.02-branches.

falter-berlin-autoupdate: Add workflow for triggering autoupdate

---

.github/workflows/entrypoint.sh
.github/workflows/formal.yml
.github/workflows/multi-arch-test-build.yml

The recent pipline was failing. Thus copying the small changeset from openwrt-packages here, to hopefully fix that,

.github: Adjust Pipeline to comply with recent OpenWrt one

---

luci/luci-app-falter-owm/Makefile
luci/luci-app-falter-owm/files/owm.sh

Minor shellcheck fixes for OWM-uploader and License addition.

Fix owm script

---

.github/workflows/multi-arch-test-build.yml

This architecture was renamed in OpenWrt at some point

github: fix powerpc test build

---

luci/luci-mod-falter/luasrc/controller/freifunk/freifunk.lua

Vorbereitungen für ein 1.4.0-Release. Ein Hoch auf den Hack-Day @ Kirchhofstr.

Luci fixes

---

.github/workflows/multi-arch-test-build.yml

.github: Update CI to use new actions

---

packages/tunspace/Makefile

Compile tested: x86_64
Run tested: n/a
Yes

tunspace: add license, remove duplication

---

packages/bgpdisco/Makefile
packages/bgpdisco/bgpdisco.conf
packages/bgpdisco/bgpdisco.init
packages/bgpdisco/bgpdisco.uc
packages/bgpdisco/bgpdisco_nameservice.conf
packages/bgpdisco/bird_config_template.ut
packages/bgpdisco/birdctl.uc
packages/bgpdisco/logger.uc
packages/bgpdisco/mrtdump.uc
packages/bgpdisco/nameservice.uc
packages/bgpdisco/plugin.uc

Kompiliert Ja/Nein:  Ja!
Läuft live Ja/Nein: Ja, to be tested in the field
Beschreibung deiner Änderungen:  Add new tool bgpdisco which aims to replace olsrd-nameservice. Ready for testing within bbb-configs.

add package bgpdisco

---

packages/bird2-babelpatch/Makefile
packages/bird2-babelpatch/files/bird.conf
packages/bird2-babelpatch/files/bird.init
packages/bird2-babelpatch/patches/000-babel-replace-internal-route-selection-by-birds-nest-v5
packages/bird2-babelpatch/patches/000-ospf-bus-error.patch
packages/bird2-babelpatch/test.sh

please merge into respective branches for 23.05 and 24.10 and main.

Add bird2 patched

---

packages/tunspace/tunspace.defaults
packages/tunspace/tunspace.uc

Compile tested: x86/64 snapshot
Run tested: x86/64 snapshot, tested that both option have the desired effect
`disabled` and `insecure_cert` didn't have any effect until now

tunspace: implement disabled and insecure_cert options

---

packages/tunspace/tunspace.uc

Kompiliert Ja/Nein: x86_64
Läuft live Ja/Nein: works correctly on x86/64 and mediatek/mt7622
Beschreibung deiner Änderungen:
IPv6 addresses get flushed when an interface is taken down. Now that we take the interface down for convenience reasons, we need to re-add the address when we bring it back up.

tunspace: re-add IPv6 address after it gets flushed

---

packages/tunspace/tunspace.uc

Kompiliert Ja/Nein: ja x86_64 24.10
Läuft live Ja/Nein: ja x86_64 24.10
Beschreibung deiner Änderungen:
Patch by @FFHener 
Some uplink routers do MAC-based access control and lock us out, because we get random MAC addresses assigned by the kernel. Now we set a stable MAC address based on our uplink interface.

tunspace: add deterministic mac
